name: Google DCA Tests

# Controls when the action will run.
on:
  [workflow_dispatch]

env:
  GOLANG_SAMPLES_PROJECT_ID: ${{ secrets.GOLANG_SAMPLES_PROJECT_ID }}
  CLIENT_CERTIFICATE: ${{ secrets.CLIENT_CERTIFICATE }}
  CREDENTIALS: ${{ secrets.CREDENTIALS }}
  GOOGLE_API_USE_MTLS: 1
  GOLANG_SAMPLES_E2E_TEST: 1
  RUN_ALL_TESTS: 0

jobs:
  pubsub-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.13.1'
    - name: Cloud Pubsub DCA Test
      env:
        TESTING_DIR: pubsub
      run: ./testing/dca/system_tests.sh
